databases:
  - name: django_render_db_novel
    plan: free
    databaseName: django_render_db_novel
    user: django_user
    region: singapore

services:
  - type: web
    plan: free
    region: singapore
    branch: main
    name: django_render_novel
    env: python
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_db_novel
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true